### ISSUE TITLE
scanline.count_scaline_intersections filter

### ISSUE THREAD

**Issue by eberrigan** [talmolab/sleap-roots#19]
When using this we should filter out the 0's since there will always be many 0's:    

scanline_intersections = sr.scanline.count_scaline_intersections(points)
filter_scanline = scanline_intersections > 0
scanline_intersections = scanline_intersections[filter_scanline]

**Comment by linwang9926** [comment]
- Instead of filtering out 0's, change the intersection number from 0 to np.nan to keep the root architecture.
- related to pull request #24
