### ISSUE TITLE
Add frame-based trait calculation function

### ISSUE THREAD

**Issue by linwang9926** [talmolab/sleap-roots#29]
Write a function to calculate 115 traits per frame with statistics if non-scalar traits.
Trait summary please refer to mermaid diagram: https://hackmd.io/@talmo/Hy7t7VS_i

**Comment by talmo** [comment]
Suggested strategy:
- Write a graph in the form of `[("source_feature1", "destination_feature1"), ("source_feature2", "destination_feature1")]`
- Instantiate the graph as a `networkx.DirectedGraph` --> run breadth-first search (BFS) traversal to get the order of the features that need to be computed
- Determine which function needs to run to compute each feature (maybe annotate each trait computation function with a decorator --> `@trait(["source1", "source2"], "dest1")`
- Then just run all the functions, in BFS order, and accumulate the results in a single dictionary

**Comment by talmo** [comment]
Some resources:
- [Creating networkx graph](https://networkx.org/documentation/stable/reference/introduction.html#graph-creation):
```
import networkx as nx
G = nx.DiGraph()
edge_list = [("a", "b"), ("a", "c"), ("b", "d")]
G.add_edges_from(edge_list)
```
- [DFS via networkx](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.breadth_first_search.bfs_tree.html#networkx.algorithms.traversal.breadth_first_search.bfs_tree):
```
G = nx.path_graph(3)
print(list(nx.bfs_tree(G, 1).edges()))
[(1, 0), (1, 2)]
H = nx.Graph()
nx.add_path(H, [0, 1, 2, 3, 4, 5, 6])
nx.add_path(H, [2, 7, 8, 9, 10])
print(sorted(list(nx.bfs_tree(H, source=3, depth_limit=3).edges())))
[(1, 0), (2, 1), (2, 7), (3, 2), (3, 4), (4, 5), (5, 6), (7, 8)]
```
- Maybe [`bfs_edges`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.breadth_first_search.bfs_edges.html#networkx.algorithms.traversal.breadth_first_search.bfs_edges)?
- [Decorators tutorial](https://realpython.com/primer-on-python-decorators/)

**Comment by linwang9926** [comment]
Add initial draft of pipelining using graph: https://github.com/talmolab/sleap-roots/pull/30
But some scalar traits did not extract, for example: I just include ellipse output as one tuple, but ellipse_a, ellipse_b, ellipse_ratio did not return.

Idea to modify the pipelining:
- Add small functions based on the scalar outputs, for example, ellipse, convex hull

**Comment by linwang9926** [comment]
Initial draft: https://github.com/talmolab/sleap-roots/pull/30
