### ISSUE TITLE
Plant trait CSVs should save as scalars

### ISSUE THREAD

**Issue by eberrigan** [talmolab/sleap-roots#33]
Currently, when saving the CSV with traits for all individual frames of a single plant (via `sleap_roots.graphpipeline.get_traits_value_plant_summary), we get cells that look like this:
![image](https://github.com/talmolab/sleap-roots/assets/106755962/31cc315a-8713-4d03-a7a7-fa5fff8de5a4)

We should save all of these as scalars without the `[]` around them wherever possible.

**Comment by linwang9926** [comment]
I modified the column with data in scalar to the value without []. For other non-scalar columns (e.g., primary_base_pt, lateral_angles_proximal) keep the non-scalar data
![image](https://github.com/talmolab/sleap-roots/assets/84240210/a544ab4d-30af-4317-9583-99782290f8d2)
