### ISSUE TITLE
Modify traits for monocots (rice)

### ISSUE THREAD

**Issue by linwang9926** [talmolab/sleap-roots#38]
1. We shouldn't be getting base related traits for monocots since it will just be noise (all bases start from the seed)
2. I see some stem width values, which is surprising for rice
3. Something is going on with the scanline. For example, scanline_intersection_counts_fprc95_median is 0 for all plants and scanline_last_ind_prc95 is all NaN.
4. change argument name of "lateral_only" to "monocots"

**Comment by linwang9926** [comment]
For each item above, the comments is:
3. use the following primary and lateral names:
```
primary_name="longest_3do_6nodes",
        lateral_name="main_3do_6nodes",
```

**Comment by eberrigan** [comment]
There should be an option for monocots to not use the primary root--for 10 DAG we do not have a primary root model. To generalize, there should be an option to not use either/or primary or lateral.
