### ISSUE TITLE
get_traits_value_plant_summary takes length of float object

### ISSUE THREAD

**Issue by eberrigan** [talmolab/sleap-roots#39]
### Summary
I am testing the pipeline using the rice data and encountered an error while running a specific test case.

### Steps to Reproduce
1. Run the test function `test_get_all_plants_traits_monocot` with the following parameters:
    - `data_folders=[r"E:\repositories\sleap-roots\tests\data\rice_3do"]`
    - `primary_name="longest_3do_6nodes"`
    - `lateral_name="main_3do_6nodes"`

### Expected Behavior
The test function should pass without any errors.

### Actual Behavior
The test fails with the following error message:
`./tests/test_graphpipeline.py::test_get_all_plants_traits_monocot Failed: [undefined]TypeError: object of type 'float' has no len()
data_folders = ['E:\\repositories\\sleap-roots\\tests\\data\\rice_3do']
primary_name = 'longest_3do_6nodes', lateral_name = 'main_3do_6nodes'

    def test_get_all_plants_traits_monocot(
        data_folders=[r"E:\repositories\sleap-roots\tests\data\rice_3do"],
        primary_name="longest_3do_6nodes",
        lateral_name="main_3do_6nodes",
    ):
>       all_traits_df = get_all_plants_traits(
            data_folders=data_folders,
            primary_name=primary_name,
            lateral_name=lateral_name,
            monocots=True,
        )

tests\test_graphpipeline.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
sleap_roots\graphpipeline.py:607: in get_all_plants_traits
    plant_traits = get_traits_value_plant_summary(
sleap_roots\graphpipeline.py:444: in get_traits_value_plant_summary
    ] = trait.apply(lambda x: np.nanmin(x) if (len(x) > 0) else np.nan)
C:\Miniconda3\envs\sleap-roots\lib\site-packages\pandas\core\series.py:4630: in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
C:\Miniconda3\envs\sleap-roots\lib\site-packages\pandas\core\apply.py:1025: in apply
    return self.apply_standard()
C:\Miniconda3\envs\sleap-roots\lib\site-packages\pandas\core\apply.py:1076: in apply_standard
    mapped = lib.map_infer(
pandas\_libs\lib.pyx:2834: in pandas._libs.lib.map_infer
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = nan

>   ] = trait.apply(lambda x: np.nanmin(x) if (len(x) > 0) else np.nan)
E   TypeError: object of type 'float' has no len()

sleap_roots\graphpipeline.py:444: TypeError`

### Error Analysis
The error can be traced back to line 444 in `graphpipeline.py` and occurs for all summarized traits of this type:
```python
data_plant_frame_summary_non_scalar[
    NON_SCALAR_TRAITS[i] + "_fmin"
] = trait.apply(lambda x: np.nanmin(x) if (len(x) > 0) else np.nan)
```

The issue arises because NaN values are of type float and do not have a length.

### Possible Solution
To address this issue, a modification is required in the code to handle NaN values appropriately. One possible solution is to add a condition to check for NaN values before applying the len() function.
`trait.apply(lambda x: np.nanmin(x) if not np.isnan(x) else np.nan)
`
However not even sure if you need this conditional.

**Comment by linwang9926** [comment]
The reason why this issue arises is some non-scalar traits of rice are scalar ones (only Nan).
I added an if condition: `not trait.isna().all()` to filter out the all nan non-scalar traits. Those summarized traits are all nans.

In addition, I also add `monocots=False` for more base-related traits, so there won't be values calculated for rice.
