### ISSUE TITLE
Scanline traits are all zeroes when monocots=True 

### ISSUE THREAD

**Issue by eberrigan** [talmolab/sleap-roots#42]
The scanline-related traits return all zeroes. This only seems to happen when monocots=True so we should make sure the lateral roots are being included in scanline traits for dicots as well.

**Comment by linwang9926** [comment]
This issue was solved in PR #43:
- In function count_scanline_intersections, use lateral_pts (main roots) for to calculate monocot traits
- In function count_scanline_intersections, use all lateral roots to calculate scanline-related traits
