### ISSUE TITLE
Add monocot pipelines

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap-roots#52]
In #51, we defined a new `Pipeline` base class and the `DicotPipeline` subclass which derives from it and implements the trait pipeline for dicot traits.

We now need to implement monocot pipelines which implement the specific logic for young and mature monocots.

These should implemented the `define_traits` and `get_initial_frame_traits` methods appropriately, including setting the appropriate `monocot` flags for individual trait computation functions, skipping traits that aren't used for those species, and dealing with renaming or missing lateral/primary/main root types.

**Comment by eberrigan** [comment]
This issue has been resolved by the merged pull request #54 (https://github.com/talmolab/sleap-roots/pull/54)). Closing this issue now.
