### ISSUE TITLE
Please I Need some clarification on primary_name="primary", lateral_name="crown" (i'm new to codes~)

### ISSUE THREAD

**Issue by sujee119** [talmolab/sleap-roots#94]
Hello!

i used the following script for testing my file,
Caputured 72 frames from my video file and used a custom ChatGPT script to convert to HD5.

import sleap_roots as sr

plant = sr.Series.load(
    "00445_6.h5",
    primary_name="primary",
    lateral_name="crown"
)
pipeline = sr.YoungerMonocotPipeline()
traits = pipeline.compute_plant_traits(plant, write_csv=True)

but im getting this error
Traceback (most recent call last):
  File "/home/duke/sleap-roots/tests/rice.py", line 3, in <module>
    plant = sr.Series.load(
            ^^^^^^^^^^^^^^^
TypeError: Series.load() got an unexpected keyword argument 'primary_name'.

i wonder what do you mean my " Specify the names of the primary and lateral roots for trait calculation"
is it the output file names with the path or input file name separated for lateral and primary roots?

Thank you!

Edit: Moreover, Making a tutorial (usually youtube) might also helpful for new users. Its much more popular these days for popularizing and promoting ease of use.

**Comment by eberrigan** [comment]
hi @sujee119,

I see you closed this issue. Sorry I haven't updated the README. I will work on that this week. I also have some jupyter notebooks with examples I need to update. I recently modified the load function to be more flexible and save a bit more information on the model used.

Let me know if you need any help!

Best,

Elizabeth
